version: '3.9'
services:
  mongo1:
    image: mongo
    container_name: mongo1
    #mem_limit: 0.1g
    storage_opt:
      size: 5G
    ports:
      - 27017:27017
    volumes:
      - ./data/db1:/data/db
    command: mongod --replSet "rs0" --port 27017 --bind_ip_all
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 100M
  mongo2:
    image: mongo
    container_name: mongo2
    #mem_limit: 0.1g
    storage_opt:
      size: 5G
    ports:
      - 27018:27018
    volumes:
      - ./data/db2:/data/db
    command: mongod --replSet "rs0" --port 27018 --bind_ip_all
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 100M
  mongo3:
    image: mongo
    container_name: mongo3
    #mem_limit: 0.1g
    storage_opt:
      size: 5G
    ports:
      - 27019:27019
    volumes:
      - ./data/db3:/data/db
    command: mongod --replSet "rs0" --port 27019 --bind_ip_all
    restart: "no"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 100M 

    #--replSet rs0
    #--memory="0.25g" --cpus="1" mongo
#rs.initiate()
#rs.add("<mongo2_container>:27017")
#rs.add("<mongo3_container>:27017")
#mongod --replSet "rs0" --bind_ip localhost
#command: mongod --replSet "rs0" --bind_ip_all --oplogSize 128